// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSaleSystem.Data;

#nullable disable

namespace SimpleSaleSystem.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleSaleSystem.Entities.Attachments", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("AttacheDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttachedFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("ImageThumbnail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MoreInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ParentID")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Attachments", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.ExceptionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CallSite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpAction")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Logged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("ExceptionLog", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Invoice", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("CallerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CreateByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("GuaranteeTime")
                        .HasColumnType("int");

                    b.Property<int>("GuaranteeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvoiceNetPrice")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<long>("InvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("InvoiceState")
                        .HasColumnType("int");

                    b.Property<decimal>("InvoiceTotalPrice")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFormal")
                        .HasColumnType("bit");

                    b.Property<string>("ManualInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoreDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<long?>("ParentInvoiceID")
                        .HasColumnType("bigint");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ProductSerials")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("SentToCustomerDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UpdateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CreateByID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ParentInvoiceID");

                    b.HasIndex("UpdateByID");

                    b.ToTable("Invoice", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.InvoiceDetails", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int?>("CountingUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(8, 6)
                        .HasColumnType("decimal(8,6)");

                    b.Property<long>("InvoiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentDetailID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ProductCount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductSerial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PureTotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int?>("StorageID")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("ID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProductID");

                    b.ToTable("InvoiceDetails", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.PageList", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<bool>("IsReport")
                        .HasColumnType("bit");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("ParentPageID")
                        .HasColumnType("smallint");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ParentPageID")
                        .HasDatabaseName("IX_PageList_ParentPageID");

                    b.ToTable("PageList", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.PagePermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanInsert")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRead")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("bit");

                    b.Property<short>("PageID")
                        .HasColumnType("smallint");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PageID")
                        .HasDatabaseName("IX_PagePermission_PageID");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IX_PagePermission_UserID");

                    b.ToTable("PagePermission", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool?>("AccountingType")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CommercialCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CreatingUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsAgency")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlackListed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonnel")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("bit");

                    b.Property<bool>("LegalPersonality")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ParentPersonID")
                        .HasColumnType("int");

                    b.Property<string>("PassportCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PersonAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonCode")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductSerials")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RegisterationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RespectTitle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubscriptionCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("CreatingUserID");

                    b.HasIndex("ParentPersonID")
                        .HasDatabaseName("IX_Person_ParentPersonID");

                    b.HasIndex("PersonName")
                        .HasDatabaseName("IX_Person_Name");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PersonName"), new[] { "IsDeleted", "IsBlackListed", "Phone", "PersonCode", "NationalCode", "Mobile" });

                    b.HasIndex("IsDeleted", "IsBlackListed")
                        .HasDatabaseName("IX_Person_Deleted_BlackListed");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IsDeleted", "IsBlackListed"), new[] { "ID", "PersonName", "Phone", "PersonCode", "NationalCode", "Mobile" });

                    b.ToTable("Person", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Product", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("BarCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CountIsEditableInSelect")
                        .HasColumnType("bit");

                    b.Property<decimal>("DefaultSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("PriceIsEditableInSelect")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<string>("ProductModel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Product", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.SystemSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("SettingName")
                        .HasDatabaseName("IX_SystemSetting_Name");

                    b.ToTable("SystemSettings", "dbo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SettingName = "DefaultTaxPercent",
                            SettingValue = "10"
                        });
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.SystemUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoginInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("OrganizationRoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserMobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("SystemUser", "dbo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Password = "EU/iHN2gTDHERoJVW/i5ZqLustJGD1egyntDOUYgSSg=",
                            UserFullName = "super",
                            UserName = "super"
                        });
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Vw_InvoiceInfo", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("CallerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateByID")
                        .HasColumnType("int");

                    b.Property<string>("CreateByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuaranteeTime")
                        .HasColumnType("int");

                    b.Property<int>("GuaranteeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvoiceNetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("InvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InvoiceTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductSerials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentToCustomerDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdateByID")
                        .HasColumnType("int");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable((string)null);

                    b.ToView("Vw_InvoiceInfoes", "dbo");
                });

            modelBuilder.Entity("SimpleSaleSystem.Server.Entities.InvoiceDefaultDescription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("InvoiceDefaultDescriptions", "dbo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "نرم افزارحضور و غیاب تحت وب -لایسنس یکساله"
                        },
                        new
                        {
                            ID = 2,
                            Description = "تنظیم روتر جهت استفاده از آی پی استاتیک"
                        },
                        new
                        {
                            ID = 3,
                            Description = "تنظیم مودم جهت استفاده از آی پی استاتیک"
                        },
                        new
                        {
                            ID = 4,
                            Description = "نرم افزار انتقال اطلاعات از برنامه دیتابیس پالیز به چارگون"
                        },
                        new
                        {
                            ID = 5,
                            Description = "نصب و راه اندازی آنلاین سنتر بصورت اینترنتی"
                        },
                        new
                        {
                            ID = 6,
                            Description = "نصب و راه اندازی اینترنتی نرم افزار حضور غیاب"
                        },
                        new
                        {
                            ID = 7,
                            Description = "لایسنس یکساله نرم افزار حضور و غیاب"
                        });
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Invoice", b =>
                {
                    b.HasOne("SimpleSaleSystem.Entities.SystemUser", "CreatingUser")
                        .WithMany("Invoices")
                        .HasForeignKey("CreateByID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSaleSystem.Entities.Person", "Person")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID");

                    b.HasOne("SimpleSaleSystem.Entities.Invoice", "ParentInvoice")
                        .WithMany("ChildInvoices")
                        .HasForeignKey("ParentInvoiceID");

                    b.HasOne("SimpleSaleSystem.Entities.SystemUser", "UpdatingUser")
                        .WithMany("Invoices_UpdateBy")
                        .HasForeignKey("UpdateByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatingUser");

                    b.Navigation("ParentInvoice");

                    b.Navigation("Person");

                    b.Navigation("UpdatingUser");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.InvoiceDetails", b =>
                {
                    b.HasOne("SimpleSaleSystem.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleSaleSystem.Entities.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.PageList", b =>
                {
                    b.HasOne("SimpleSaleSystem.Entities.PageList", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageID");

                    b.Navigation("ParentPage");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.PagePermission", b =>
                {
                    b.HasOne("SimpleSaleSystem.Entities.PageList", "PageList")
                        .WithMany("PagePermissions")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSaleSystem.Entities.SystemUser", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PageList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Person", b =>
                {
                    b.HasOne("SimpleSaleSystem.Entities.SystemUser", "CreatingUser")
                        .WithMany("CreatedPeople")
                        .HasForeignKey("CreatingUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSaleSystem.Entities.Person", "ParentPerson")
                        .WithMany("ChildPeople")
                        .HasForeignKey("ParentPersonID");

                    b.Navigation("CreatingUser");

                    b.Navigation("ParentPerson");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Invoice", b =>
                {
                    b.Navigation("ChildInvoices");

                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.PageList", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Person", b =>
                {
                    b.Navigation("ChildPeople");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.Product", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("SimpleSaleSystem.Entities.SystemUser", b =>
                {
                    b.Navigation("CreatedPeople");

                    b.Navigation("Invoices");

                    b.Navigation("Invoices_UpdateBy");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
